/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pet_addPet } from "../../funcs/pet_addPet.js";
import { Pet$zodSchema } from "../../models/components/pet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: Pet$zodSchema,
};

export const tool$pet_addPet: ToolDefinition<typeof args> = {
  name: "pet-add-pet",
  description: `Add a new pet to the store

Add a new pet to the store`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pet_addPet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
