/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pet_findPetsByStatus } from "../../funcs/pet_findPetsByStatus.js";
import { FindPetsByStatusRequest$zodSchema } from "../../models/operations/findpetsbystatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FindPetsByStatusRequest$zodSchema.optional(),
};

export const tool$pet_findPetsByStatus: ToolDefinition<typeof args> = {
  name: "pet-find-pets-by-status",
  description: `Finds Pets by status

Multiple status values can be provided with comma separated strings`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pet_findPetsByStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
