/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pet_uploadFile } from "../../funcs/pet_uploadFile.js";
import { UploadFileRequest$zodSchema } from "../../models/operations/uploadfile.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadFileRequest$zodSchema,
};

export const tool$pet_uploadFile: ToolDefinition<typeof args> = {
  name: "pet-upload-file",
  description: `uploads an image`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pet_uploadFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
