/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pet_deletePet } from "../../funcs/pet_deletePet.js";
import { DeletePetRequest$zodSchema } from "../../models/operations/deletepet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePetRequest$zodSchema,
};

export const tool$pet_deletePet: ToolDefinition<typeof args> = {
  name: "pet-delete-pet",
  description: `Deletes a pet`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await pet_deletePet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
