/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petGetPetById } from "../../funcs/petGetPetById.js";
import { GetPetByIdRequest$zodSchema } from "../../models/getpetbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPetByIdRequest$zodSchema,
};

export const tool$petGetPetById: ToolDefinition<typeof args> = {
  name: "pet-get-pet-by-id",
  description: `Find pet by ID

Returns a single pet`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petGetPetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
