/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petUpdatePet } from "../../funcs/petUpdatePet.js";
import { Pet$zodSchema } from "../../models/pet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: Pet$zodSchema,
};

export const tool$petUpdatePet: ToolDefinition<typeof args> = {
  name: "pet-update-pet",
  description: `Update an existing pet

Update an existing pet by Id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petUpdatePet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
