/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { store_deleteOrder } from "../../funcs/store_deleteOrder.js";
import { DeleteOrderRequest$zodSchema } from "../../models/operations/deleteorder.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteOrderRequest$zodSchema,
};

export const tool$store_deleteOrder: ToolDefinition<typeof args> = {
  name: "store-delete-order",
  description: `Delete purchase order by ID

For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await store_deleteOrder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
