/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { store_getInventory } from "../../funcs/store_getInventory.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$store_getInventory: ToolDefinition = {
  name: "store-get-inventory",
  description: `Returns pet inventories by status

Returns a map of status codes to quantities`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await store_getInventory(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
