/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { store_placeOrder } from "../../funcs/store_placeOrder.js";
import { Order$zodSchema } from "../../models/components/order.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: Order$zodSchema.optional(),
};

export const tool$store_placeOrder: ToolDefinition<typeof args> = {
  name: "store-place-order",
  description: `Place an order for a pet

Place a new order in the store`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await store_placeOrder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
