/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { user_logoutUser } from "../../funcs/user_logoutUser.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$user_logoutUser: ToolDefinition = {
  name: "user-logout-user",
  description: `Logs out current logged in user session`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await user_logoutUser(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
