/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { user_updateUser } from "../../funcs/user_updateUser.js";
import { UpdateUserRequest$zodSchema } from "../../models/operations/updateuser.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateUserRequest$zodSchema,
};

export const tool$user_updateUser: ToolDefinition<typeof args> = {
  name: "user-update-user",
  description: `Update user

This can only be done by the logged in user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await user_updateUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
