/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { user_createUser } from "../../funcs/user_createUser.js";
import { User$zodSchema } from "../../models/components/user.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: User$zodSchema.optional(),
};

export const tool$user_createUser: ToolDefinition<typeof args> = {
  name: "user-create-user",
  description: `Create user

This can only be done by the logged in user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await user_createUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
