/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { user_getUserByName } from "../../funcs/user_getUserByName.js";
import { GetUserByNameRequest$zodSchema } from "../../models/operations/getuserbyname.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUserByNameRequest$zodSchema,
};

export const tool$user_getUserByName: ToolDefinition<typeof args> = {
  name: "user-get-user-by-name",
  description: `Get user by user name`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await user_getUserByName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
