/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { user_deleteUser } from "../../funcs/user_deleteUser.js";
import { DeleteUserRequest$zodSchema } from "../../models/operations/deleteuser.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteUserRequest$zodSchema,
};

export const tool$user_deleteUser: ToolDefinition<typeof args> = {
  name: "user-delete-user",
  description: `Delete user

This can only be done by the logged in user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await user_deleteUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
