/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { PetstoreCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$pet_addPet } from "./tools/pet_addPet.js";
import { tool$pet_deletePet } from "./tools/pet_deletePet.js";
import { tool$pet_findPetsByStatus } from "./tools/pet_findPetsByStatus.js";
import { tool$pet_findPetsByTags } from "./tools/pet_findPetsByTags.js";
import { tool$pet_getPetById } from "./tools/pet_getPetById.js";
import { tool$pet_updatePet } from "./tools/pet_updatePet.js";
import { tool$pet_uploadFile } from "./tools/pet_uploadFile.js";
import { tool$store_deleteOrder } from "./tools/store_deleteOrder.js";
import { tool$store_getInventory } from "./tools/store_getInventory.js";
import { tool$store_getOrderById } from "./tools/store_getOrderById.js";
import { tool$store_placeOrder } from "./tools/store_placeOrder.js";
import { tool$user_createUser } from "./tools/user_createUser.js";
import { tool$user_createUsersWithListInput } from "./tools/user_createUsersWithListInput.js";
import { tool$user_deleteUser } from "./tools/user_deleteUser.js";
import { tool$user_getUserByName } from "./tools/user_getUserByName.js";
import { tool$user_loginUser } from "./tools/user_loginUser.js";
import { tool$user_logoutUser } from "./tools/user_logoutUser.js";
import { tool$user_updateUser } from "./tools/user_updateUser.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  environment?: SDKOptions["environment"] | undefined;
}) {
  const server = new McpServer({
    name: "Petstore",
    version: "0.0.2",
  });

  const client = new PetstoreCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
    environment: deps.environment,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$pet_updatePet);
  tool(tool$pet_addPet);
  tool(tool$pet_findPetsByStatus);
  tool(tool$pet_findPetsByTags);
  tool(tool$pet_getPetById);
  tool(tool$pet_deletePet);
  tool(tool$pet_uploadFile);
  tool(tool$store_getInventory);
  tool(tool$store_placeOrder);
  tool(tool$store_getOrderById);
  tool(tool$store_deleteOrder);
  tool(tool$user_createUser);
  tool(tool$user_createUsersWithListInput);
  tool(tool$user_loginUser);
  tool(tool$user_logoutUser);
  tool(tool$user_getUserByName);
  tool(tool$user_updateUser);
  tool(tool$user_deleteUser);

  return server;
}
