/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Pet, Pet$zodSchema } from "../components/pet.js";

export type AddPetResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Pet?: Pet | undefined;
};

export const AddPetResponse$zodSchema: z.ZodType<
  AddPetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Pet: Pet$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
