/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "../components/user.js";

export type CreateUsersWithListInputResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  User?: User | undefined;
};

export const CreateUsersWithListInputResponse$zodSchema: z.ZodType<
  CreateUsersWithListInputResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  User: User$zodSchema.optional(),
});
