/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "../components/apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "../components/apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "../components/apierrorunauthorized.js";
import { User, User$zodSchema } from "../components/user.js";

export type DeleteUserRequest = { username: string };

export const DeleteUserRequest$zodSchema: z.ZodType<
  DeleteUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string().describe("The name that needs to be deleted"),
});

export type DeleteUserResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  User?: User | undefined;
  ApiErrorInvalidInput?: ApiErrorInvalidInput | undefined;
  ApiErrorUnauthorized?: ApiErrorUnauthorized | undefined;
  ApiErrorNotFound?: ApiErrorNotFound | undefined;
};

export const DeleteUserResponse$zodSchema: z.ZodType<
  DeleteUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiErrorInvalidInput: ApiErrorInvalidInput$zodSchema.optional(),
  ApiErrorNotFound: ApiErrorNotFound$zodSchema.optional(),
  ApiErrorUnauthorized: ApiErrorUnauthorized$zodSchema.optional(),
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  User: User$zodSchema.optional(),
});
