/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LogoutUserResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const LogoutUserResponse$zodSchema: z.ZodType<
  LogoutUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
