/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "../components/user.js";

export type UpdateUserRequest = { username: string; User?: User | undefined };

export const UpdateUserRequest$zodSchema: z.ZodType<
  UpdateUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  User: User$zodSchema.optional(),
  username: z.string().describe("name that needs to be updated"),
});

export type UpdateUserResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const UpdateUserResponse$zodSchema: z.ZodType<
  UpdateUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
