/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiResponse,
  ApiResponse$zodSchema,
} from "../components/apiresponse.js";

export type UploadFileRequest = {
  petId: number;
  additionalMetadata?: string | undefined;
  RequestBody?: Uint8Array | string | undefined;
};

export const UploadFileRequest$zodSchema: z.ZodType<
  UploadFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.string().base64().optional(),
  additionalMetadata: z.string().describe("Additional Metadata").optional(),
  petId: z.number().int().describe("ID of pet to update"),
});

export type UploadFileResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ApiResponse?: ApiResponse | undefined;
};

export const UploadFileResponse$zodSchema: z.ZodType<
  UploadFileResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiResponse: ApiResponse$zodSchema.optional(),
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
