/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Not Found error
 */
export type ApiErrorNotFound = { status: number; error: string; code: string };

export const ApiErrorNotFound$zodSchema: z.ZodType<
  ApiErrorNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  error: z.string(),
  status: z.number().int(),
}).describe("Not Found error");
