/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Category = { id?: number | undefined; name?: string | undefined };

export const Category$zodSchema: z.ZodType<Category, z.ZodTypeDef, unknown> = z
  .object({
    id: z.number().int().optional(),
    name: z.string().optional(),
  });
