/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

/**
 * Status values that need to be considered for filter
 */
export const FindPetsByStatusStatus$zodSchema = z.enum([
  "available",
  "pending",
  "sold",
]).describe("Status values that need to be considered for filter");

export type FindPetsByStatusStatus = z.infer<
  typeof FindPetsByStatusStatus$zodSchema
>;

export type FindPetsByStatusRequest = {
  status?: FindPetsByStatusStatus | undefined;
};

export const FindPetsByStatusRequest$zodSchema: z.ZodType<
  FindPetsByStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: FindPetsByStatusStatus$zodSchema.default("available"),
});

export type FindPetsByStatusResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Pets?: Array<Pet> | undefined;
  ApiErrorInvalidInput?: ApiErrorInvalidInput | undefined;
  ApiErrorUnauthorized?: ApiErrorUnauthorized | undefined;
  ApiErrorNotFound?: ApiErrorNotFound | undefined;
};

export const FindPetsByStatusResponse$zodSchema: z.ZodType<
  FindPetsByStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiErrorInvalidInput: ApiErrorInvalidInput$zodSchema.optional(),
  ApiErrorNotFound: ApiErrorNotFound$zodSchema.optional(),
  ApiErrorUnauthorized: ApiErrorUnauthorized$zodSchema.optional(),
  ContentType: z.string(),
  Pets: z.array(Pet$zodSchema).describe("successful operation").optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
