/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Order Status
 */
export const OrderStatus$zodSchema = z.enum([
  "placed",
  "approved",
  "delivered",
]).describe("Order Status");

export type OrderStatus = z.infer<typeof OrderStatus$zodSchema>;

export type Order = {
  id?: number | undefined;
  petId?: number | undefined;
  quantity?: number | undefined;
  shipDate?: string | undefined;
  status?: OrderStatus | undefined;
  complete?: boolean | undefined;
};

export const Order$zodSchema: z.ZodType<Order, z.ZodTypeDef, unknown> = z
  .object({
    complete: z.boolean().optional(),
    id: z.number().int().optional(),
    petId: z.number().int().optional(),
    quantity: z.number().int().optional(),
    shipDate: z.string().datetime({ offset: true }).optional(),
    status: OrderStatus$zodSchema.optional(),
  });
