/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Category, Category$zodSchema } from "./category.js";
import { Tag, Tag$zodSchema } from "./tag.js";

/**
 * pet status in the store
 */
export const PetStatus$zodSchema = z.enum([
  "available",
  "pending",
  "sold",
]).describe("pet status in the store");

export type PetStatus = z.infer<typeof PetStatus$zodSchema>;

export type Pet = {
  id?: number | undefined;
  name: string;
  category?: Category | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag> | undefined;
  status?: PetStatus | undefined;
};

export const Pet$zodSchema: z.ZodType<Pet, z.ZodTypeDef, unknown> = z.object({
  category: Category$zodSchema.optional(),
  id: z.number().int().optional(),
  name: z.string(),
  photoUrls: z.array(z.string()),
  status: PetStatus$zodSchema.optional(),
  tags: z.array(Tag$zodSchema).optional(),
});
