/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

export type UpdatePetResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Pet?: Pet | undefined;
  ApiErrorInvalidInput?: ApiErrorInvalidInput | undefined;
  ApiErrorUnauthorized?: ApiErrorUnauthorized | undefined;
  ApiErrorNotFound?: ApiErrorNotFound | undefined;
};

export const UpdatePetResponse$zodSchema: z.ZodType<
  UpdatePetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiErrorInvalidInput: ApiErrorInvalidInput$zodSchema.optional(),
  ApiErrorNotFound: ApiErrorNotFound$zodSchema.optional(),
  ApiErrorUnauthorized: ApiErrorUnauthorized$zodSchema.optional(),
  ContentType: z.string(),
  Pet: Pet$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
