/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Tag = { id?: number | undefined; name?: string | undefined };

export const Tag$zodSchema: z.ZodType<Tag, z.ZodTypeDef, unknown> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional(),
});
